course = 'centria-csharp-advanced-summer-2023'
[exercises.part_08-001_nicknames]
id = 204546
checksum = '3c02948c612c089f41ba69a26ed7ffe4'

[exercises.part_08-002_abbreviations]
id = 204548
checksum = 'a3ea2b6e3363ee2ea9f38d48af0cec5b'

[exercises.part_08-003_print_dictionary_keys]
id = 204552
checksum = 'fa42da204314b40c68367d264077bf3f'

[exercises.part_08-004_book_dictionary]
id = 204550
checksum = '3e08a536d9d7dd48414e075ce1ee597d'

[exercises.part_08-005_i_owe_you]
id = 204547
checksum = '698297e39707fb922691dd13f048f7e5'

[exercises.part_08-006_same_date]
id = 204554
checksum = '9b529c89b6d76685f86781030f633a5e'

[exercises.part_08-007_vehicle_registry]
id = 204553
checksum = '83e20b1632929bf98c4f49aaa03e3a04'

[exercises.part_08-008_dictionary_of_many_translations]
id = 204549
checksum = '3d115ecd2f127c538d38f437acbde5ee'

[exercises.part_08-009_storage_facility]
id = 204551
checksum = '667ada3d922a34ced89f640cb28e9fa1'

[exercises.part_09-001_abc]
id = 204540
checksum = '6317e23fd9a864752e859d737cbd12df'

[exercises.part_09-002_person_and_subclasses]
id = 204533
checksum = '596e25bd022db8435dad1723ff5b6fa6'

[exercises.part_09-003_warehousing]
id = 204534
checksum = 'ae4569edae75ca5702c69c4096a3e7e9'

[exercises.part_09-004_different_boxes]
id = 204536
checksum = '847e98ad44cfcff9f78b24866edbb03b'

[exercises.part_09-005_taco_boxes]
id = 204535
checksum = '947c087ad4b98b44dfb301e842ad3c88'

[exercises.part_09-006_interface_in_a_box]
id = 204537
checksum = 'ef461033693b56bc0e0681796d68f02c'

[exercises.part_09-007_herds]
id = 204539
checksum = '30cfb3b6d14721e533f0c8aa82f36baf'

[exercises.part_09-008_animals]
id = 204538
checksum = '182b4778545faa47c08975d162282a28'

[exercises.part_10-001_wage_order]
id = 204543
checksum = 'a7a5682d2515e78527dd42a01faa6181'

[exercises.part_10-002_students_in_alphabetical_order]
id = 204542
checksum = '63ce80453299b83cf616303609587532'

[exercises.part_10-003_literacy_comparison]
id = 204544
checksum = 'be61d07f7a89aa1cedb6edcf84fff34c'

[exercises.part_10-004_regular_expressions_checker]
id = 204545
checksum = '4222364967a27d9ab924c09a64fe761b'

[exercises.part_10-005_sort_them_cards]
id = 204541
checksum = 'f74e3173702f91fb1a6fbb9892701ef2'
